package org.accada.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator Wed Jan 30
 * 15:43:44 CET 2008 Generated source version: 2.0.4-incubator
 */

@WebFault(name = "SubscribeNotPermittedException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SubscribeNotPermittedExceptionResponse extends Exception {
    public static final long serialVersionUID = 20080130154344L;

    private org.accada.epcis.soap.model.SubscribeNotPermittedException subscribeNotPermittedException;

    public SubscribeNotPermittedExceptionResponse() {
        super();
    }

    public SubscribeNotPermittedExceptionResponse(String message) {
        super(message);
    }

    public SubscribeNotPermittedExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscribeNotPermittedExceptionResponse(String message,
            org.accada.epcis.soap.model.SubscribeNotPermittedException subscribeNotPermittedException) {
        super(message);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public SubscribeNotPermittedExceptionResponse(String message,
            org.accada.epcis.soap.model.SubscribeNotPermittedException subscribeNotPermittedException, Throwable cause) {
        super(message, cause);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public org.accada.epcis.soap.model.SubscribeNotPermittedException getFaultInfo() {
        return this.subscribeNotPermittedException;
    }
}
