package org.accada.epcis.queryclient;

import java.util.ArrayList;
import java.util.List;

import org.accada.epcis.soapapi.QueryParam;

/**
 * Implements a class that holds examples for the EPCIS Query Interface Client.
 * Uses class QueryInterfaceQueryExampleExample to store them.
 * 
 * @author David Gubler
 */
public class QueryClientGuiExampleQueries {
    /**
     * Vector that holds all the examples.
     */
    private List<Query> examples = new ArrayList<Query>();

    /**
     * Constructor. Sets up the examples. Add examples here if you wish.
     */
    public QueryClientGuiExampleQueries() {
        Query ex = new Query();
        ex.setDescription("Search for an aggregation onto a certain pallet");
        ex.setReturnAggregationEvents(true);
        ex.getQueryParameters().add(new QueryParam("EQ_action", "ADD"));
        ex.getQueryParameters().add(
                new QueryParam("MATCH_parentID", "urn:x:bar:5:036544:007325"));
        examples.add(ex);

        ex = new Query();
        ex.setDescription("Find out what happened to a certain EPC after a "
                + "certain date");
        ex.setReturnObjectEvents(true);
        ex.getQueryParameters().add(
                new QueryParam("GE_eventTime", "2006-01-01T05:20:31"));
        ex.getQueryParameters().add(
                new QueryParam("MATCH_epc",
                        "urn:epc:id:sgtin:0034000.987650.2686"));
        examples.add(ex);

        ex = new Query();
        ex.setDescription("Get all events generated by a certain reader");
        ex.setReturnObjectEvents(true);
        ex.setReturnAggregationEvents(true);
        ex.setReturnQuantityEvents(true);
        ex.setReturnTransactionEvents(true);
        /*
         * ex.getQueryParametersVector() .add(new QueryParam("GE_eventTime",
         * "2006-02-14T00:00:00")); ex.getQueryParametersVector() .add(new
         * QueryParam("LT_eventTime", "2006-02-15T00:00:00"));
         */
        ex.getQueryParameters().add(
                new QueryParam("EQ_readPoint",
                        "urn:epcglobal:fmcg:ssl:0037000.00729.210,414"));
        examples.add(ex);

        /*
         * Example disabled - not supported by GUI see
         * QueryInterfaceClientSwingGui.generateParamHashMap() ex = new
         * QueryInterfaceQueryExample(); ex.setDescription("Get status
         * information about shipment"); ex.setReturnObjectEvents(true);
         * ex.setReturnTransactionEvents(true);
         * ex.getQueryParametersVector().add(new QueryParam("EQ_bizTransaction",
         * "http://transaction.acme.com/po/12345678")); examples.add(ex);
         */

        ex = new Query();
        ex.setDescription("Find out when a certain EPC was shipped");
        ex.setReturnObjectEvents(true);
        ex.getQueryParameters().add(new QueryParam("EQ_action", "OBSERVE"));
        ex.getQueryParameters().add(
                new QueryParam("EQ_bizStep",
                        "urn:epcglobal:epcis:bizstep:fmcg:shipping"));
        ex.getQueryParameters().add(
                new QueryParam("MATCH_epc",
                        "urn:epc:id:sgtin:0057000.123430.2028"));
        examples.add(ex);

        /*
         * ex = new QueryInterfaceQueryExample(); ex.setDescription("Find all
         * events caused by two EPCs (only " + "ObjectEvent and AggragationEvent
         * may be queried this way)"); ex.setReturnObjectEvents(true);
         * ex.setReturnAggregationEvents(true);
         * ex.getQueryParametersVector().add(new QueryParam("MATCH_epc",
         * "urn:epc:id:sgtin:0057000.123430.2028 " +
         * "urn:epc:id:sgtin:0034000.987650.3542"));
         * ex.getQueryParametersVector().add(new QueryParam("MATCH_childEPC",
         * "urn:epc:id:sgtin:0057000.123430.2028 " +
         * "urn:epc:id:sgtin:0034000.987650.3542")); examples.add(ex);
         */

        ex = new Query();
        ex.setDescription("Find all EPCs that have been in repair during 2006");
        ex.setReturnObjectEvents(true);
        ex.getQueryParameters().add(new QueryParam("EQ_action", "OBSERVE"));
        ex.getQueryParameters().add(
                new QueryParam("GE_eventTime", "2006-01-01T00:00:00"));
        ex.getQueryParameters().add(
                new QueryParam("LT_eventTime", "2007-01-01T00:00:00"));
        ex.getQueryParameters().add(
                new QueryParam("EQ_disposition",
                        "urn:epcglobal:epcis:disp:fmcg:inrepair"));
        examples.add(ex);
    }

    /**
     * @return A List of Query.
     */
    public List<Query> getExamples() {
        return examples;
    }
}
