package org.fosstrak.epcis.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.8 Wed Jun 02 14:58:00 CEST 2010
 * Generated source version: 2.2.8
 */

@WebService(targetNamespace = "urn:epcglobal:epcis:wsdl:1", name = "EPCISServicePortType")
@XmlSeeAlso( { org.fosstrak.epcis.model.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EPCISServicePortType {

    @WebResult(name = "GetQueryNamesResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getQueryNamesReturn")
    @WebMethod
    public org.fosstrak.epcis.model.ArrayOfString getQueryNames(
            @WebParam(partName = "parms", name = "GetQueryNames", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.EmptyParms parms)
            throws ImplementationExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse;

    @WebResult(name = "UnsubscribeResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "unsubscribeReturn")
    @WebMethod
    public org.fosstrak.epcis.model.VoidHolder unsubscribe(
            @WebParam(partName = "parms", name = "Unsubscribe", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.Unsubscribe parms)
            throws NoSuchSubscriptionExceptionResponse, ImplementationExceptionResponse, SecurityExceptionResponse,
            ValidationExceptionResponse;

    @WebResult(name = "QueryResults", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "pollReturn")
    @WebMethod
    public org.fosstrak.epcis.model.QueryResults poll(
            @WebParam(partName = "parms", name = "Poll", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.Poll parms)
            throws QueryTooLargeExceptionResponse, ImplementationExceptionResponse, NoSuchNameExceptionResponse,
            QueryTooComplexExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse,
            QueryParameterExceptionResponse;

    @WebResult(name = "SubscribeResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "subscribeReturn")
    @WebMethod
    public org.fosstrak.epcis.model.VoidHolder subscribe(
            @WebParam(partName = "parms", name = "Subscribe", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.Subscribe parms)
            throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, QueryTooComplexExceptionResponse,
            SubscriptionControlsExceptionResponse, SubscribeNotPermittedExceptionResponse,
            DuplicateSubscriptionExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse,
            InvalidURIExceptionResponse, QueryParameterExceptionResponse;

    @WebResult(name = "GetVendorVersionResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getVendorVersionReturn")
    @WebMethod
    public java.lang.String getVendorVersion(
            @WebParam(partName = "parms", name = "GetVendorVersion", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.EmptyParms parms)
            throws ImplementationExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse;

    @WebResult(name = "GetStandardVersionResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getStandardVersionReturn")
    @WebMethod
    public java.lang.String getStandardVersion(
            @WebParam(partName = "parms", name = "GetStandardVersion", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.EmptyParms parms)
            throws ImplementationExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse;

    @WebResult(name = "GetSubscriptionIDsResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getSubscriptionIDsReturn")
    @WebMethod
    public org.fosstrak.epcis.model.ArrayOfString getSubscriptionIDs(
            @WebParam(partName = "parms", name = "GetSubscriptionIDs", targetNamespace = "urn:epcglobal:epcis-query:xsd:1") org.fosstrak.epcis.model.GetSubscriptionIDs parms)
            throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, SecurityExceptionResponse,
            ValidationExceptionResponse;
}
