package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator Wed Jan 30
 * 15:43:44 CET 2008 Generated source version: 2.0.4-incubator
 */

@WebFault(name = "ImplementationException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class ImplementationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20080130154344L;

    private org.fosstrak.epcis.model.ImplementationException implementationException;

    public ImplementationExceptionResponse() {
        super();
    }

    public ImplementationExceptionResponse(String message) {
        super(message);
    }

    public ImplementationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImplementationExceptionResponse(String message,
            org.fosstrak.epcis.model.ImplementationException implementationException) {
        super(message);
        this.implementationException = implementationException;
    }

    public ImplementationExceptionResponse(String message,
            org.fosstrak.epcis.model.ImplementationException implementationException, Throwable cause) {
        super(message, cause);
        this.implementationException = implementationException;
    }

    public org.fosstrak.epcis.model.ImplementationException getFaultInfo() {
        return this.implementationException;
    }
}
