package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.2.8 Wed Jun 02 14:57:59 CEST 2010
 * Generated source version: 2.2.8
 */

@WebFault(name = "NoSuchSubscriptionException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class NoSuchSubscriptionExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100602145759L;

    private org.fosstrak.epcis.model.NoSuchSubscriptionException noSuchSubscriptionException;

    public NoSuchSubscriptionExceptionResponse() {
        super();
    }

    public NoSuchSubscriptionExceptionResponse(String message) {
        super(message);
    }

    public NoSuchSubscriptionExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSubscriptionExceptionResponse(String message,
            org.fosstrak.epcis.model.NoSuchSubscriptionException noSuchSubscriptionException) {
        super(message);
        this.noSuchSubscriptionException = noSuchSubscriptionException;
    }

    public NoSuchSubscriptionExceptionResponse(String message,
            org.fosstrak.epcis.model.NoSuchSubscriptionException noSuchSubscriptionException, Throwable cause) {
        super(message, cause);
        this.noSuchSubscriptionException = noSuchSubscriptionException;
    }

    public org.fosstrak.epcis.model.NoSuchSubscriptionException getFaultInfo() {
        return this.noSuchSubscriptionException;
    }
}
