package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.2.8 Wed Jun 02 14:57:59 CEST 2010
 * Generated source version: 2.2.8
 */

@WebFault(name = "QueryTooLargeException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class QueryTooLargeExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100602145759L;

    private org.fosstrak.epcis.model.QueryTooLargeException queryTooLargeException;

    public QueryTooLargeExceptionResponse() {
        super();
    }

    public QueryTooLargeExceptionResponse(String message) {
        super(message);
    }

    public QueryTooLargeExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryTooLargeExceptionResponse(String message,
            org.fosstrak.epcis.model.QueryTooLargeException queryTooLargeException) {
        super(message);
        this.queryTooLargeException = queryTooLargeException;
    }

    public QueryTooLargeExceptionResponse(String message,
            org.fosstrak.epcis.model.QueryTooLargeException queryTooLargeException, Throwable cause) {
        super(message, cause);
        this.queryTooLargeException = queryTooLargeException;
    }

    public org.fosstrak.epcis.model.QueryTooLargeException getFaultInfo() {
        return this.queryTooLargeException;
    }
}
