package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.2.9 Tue Jul 06 14:13:27 CEST 2010
 * Generated source version: 2.2.9
 */

@WebFault(name = "SubscriptionControlsException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SubscriptionControlsExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100706141327L;

    private org.fosstrak.epcis.model.SubscriptionControlsException subscriptionControlsException;

    public SubscriptionControlsExceptionResponse() {
        super();
    }

    public SubscriptionControlsExceptionResponse(String message) {
        super(message);
    }

    public SubscriptionControlsExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscriptionControlsExceptionResponse(String message,
            org.fosstrak.epcis.model.SubscriptionControlsException subscriptionControlsException) {
        super(message);
        this.subscriptionControlsException = subscriptionControlsException;
    }

    public SubscriptionControlsExceptionResponse(String message,
            org.fosstrak.epcis.model.SubscriptionControlsException subscriptionControlsException, Throwable cause) {
        super(message, cause);
        this.subscriptionControlsException = subscriptionControlsException;
    }

    public org.fosstrak.epcis.model.SubscriptionControlsException getFaultInfo() {
        return this.subscriptionControlsException;
    }
}
