package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.2.8 Wed Jun 02 14:58:00 CEST 2010
 * Generated source version: 2.2.8
 */

@WebFault(name = "SubscribeNotPermittedException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class SubscribeNotPermittedExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100602145800L;

    private org.fosstrak.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException;

    public SubscribeNotPermittedExceptionResponse() {
        super();
    }

    public SubscribeNotPermittedExceptionResponse(String message) {
        super(message);
    }

    public SubscribeNotPermittedExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscribeNotPermittedExceptionResponse(String message,
            org.fosstrak.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException) {
        super(message);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public SubscribeNotPermittedExceptionResponse(String message,
            org.fosstrak.epcis.model.SubscribeNotPermittedException subscribeNotPermittedException, Throwable cause) {
        super(message, cause);
        this.subscribeNotPermittedException = subscribeNotPermittedException;
    }

    public org.fosstrak.epcis.model.SubscribeNotPermittedException getFaultInfo() {
        return this.subscribeNotPermittedException;
    }
}
