package org.accada.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator Wed Jan 30
 * 15:43:44 CET 2008 Generated source version: 2.0.4-incubator
 */

@WebFault(name = "ValidationException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class ValidationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20080130154344L;

    private org.accada.epcis.model.ValidationException validationException;

    public ValidationExceptionResponse() {
        super();
    }

    public ValidationExceptionResponse(String message) {
        super(message);
    }

    public ValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionResponse(String message, org.accada.epcis.model.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionResponse(String message, org.accada.epcis.model.ValidationException validationException,
            Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public org.accada.epcis.model.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
