package org.fosstrak.epcis.soap;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.2.8 Wed Jun 02 14:57:59 CEST 2010
 * Generated source version: 2.2.8
 */

@WebFault(name = "ValidationException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class ValidationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100602145759L;

    private org.fosstrak.epcis.model.ValidationException validationException;

    public ValidationExceptionResponse() {
        super();
    }

    public ValidationExceptionResponse(String message) {
        super(message);
    }

    public ValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionResponse(String message, org.fosstrak.epcis.model.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionResponse(String message,
            org.fosstrak.epcis.model.ValidationException validationException, Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public org.fosstrak.epcis.model.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
